name: Build and deploy emscripten-wasm32

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 4.0.14
          
    - name: Bootstrap vcpkg
      run: |
        ./extern/vcpkg/bootstrap-vcpkg.sh -disableMetrics

    - name: Configure CMake
      run: cmake --preset wasm32-emscripten

    - name: Build
      run: cmake --build --preset wasm32-emscripten -j$(nproc)
